### ISSUE TITLE
How to add public key via gogs UI

### ISSUE THREAD

**Issue by KernowCode** [ssherwood/alm-box#1]
In your instructions you state
"Add the public ssh key generated for TeamCity in the ./keys folder"

How is this done?

**Comment by ssherwood** [comment]
Sorry, its been a while, but I I think that the keys are created by running the init.sh script.  This should have created a "hidden" .keys folder where you can just copy/paste them as needed.  Specifically, I think there is a teamcity_agent folder where the keys should should live.

**Comment by KernowCode** [comment]
Sorry, the part when setting up gogs where is the ./keys folder I am looking at the gogs UI and see nowhere to add the public ssh key to gogs.  Sorry this part is not clear to me.

You mention copy and paste them but where in gogs?

**Comment by KernowCode** [comment]
I think this article helps https://pdemro.com/gogs-how-to-set-up-an-ssh-key-when-using-docker-bonus-caddy-config/

Got to Your Profile > Yout Settings > SSH Keys > Add Key
